openapi: '3.0.2'
info:
  title: CV Prica API
  version: '1.0'
  description: CV Prica API specifikacija
servers:
  - url: https://api.server.test/v1


paths:
  /employee:
    get:
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '401':
          description: Unauthenticated
        '403':
          description: Forbidden
        '404':
          description: Not found
        '5XX':
          description: Unexpected error
